2021-09-29 10:43:08,265 INFO    MainThread:12568 [wandb_setup.py:_flush():69] setting env: {}
2021-09-29 10:43:08,265 INFO    MainThread:12568 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '8bbaf831241b8525faf8ba0890cc99d295161186'}
2021-09-29 10:43:08,265 INFO    MainThread:12568 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '8bbaf831241b8525faf8ba0890cc99d295161186'}
2021-09-29 10:43:08,265 INFO    MainThread:12568 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-29 10:43:08,265 INFO    MainThread:12568 [wandb_init.py:_log_setup():348] Logging user logs to /root/konst/ml-utils/training/ner_employment/wandb/run-20210929_104308-279gpl1n/logs/debug.log
2021-09-29 10:43:08,265 INFO    MainThread:12568 [wandb_init.py:_log_setup():349] Logging internal logs to /root/konst/ml-utils/training/ner_employment/wandb/run-20210929_104308-279gpl1n/logs/debug-internal.log
2021-09-29 10:43:08,265 INFO    MainThread:12568 [wandb_init.py:init():381] calling init triggers
2021-09-29 10:43:08,266 INFO    MainThread:12568 [wandb_init.py:init():388] wandb.init called with sweep_config: {}
config: {'data_path': '/root/konst/data/nerus_lenta/news_ner_dataset.csv', 'checkpoint_path': '/root/konst/model_checkpoints/ner_employment', 'model_path': '', 'batch_size': 128, 'epochs': 100, 'start_epoch': 0, 'test_size': 0.05, 'lam': 0, 'patience': 2, 'factor': 0.5, 'use_wandb': True, 'lr': 0.001, 'save_at': 1, 'adjust_lr_every': 1, 'num_workers': 4}
2021-09-29 10:43:08,266 INFO    MainThread:12568 [wandb_init.py:init():430] starting backend
2021-09-29 10:43:08,266 INFO    MainThread:12568 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-29 10:43:08,271 INFO    MainThread:12568 [backend.py:ensure_launched():135] starting backend process...
2021-09-29 10:43:08,274 INFO    MainThread:12568 [backend.py:ensure_launched():140] started backend process with pid: 12586
2021-09-29 10:43:08,275 INFO    MainThread:12568 [wandb_init.py:init():435] backend started and connected
2021-09-29 10:43:08,278 INFO    MainThread:12568 [wandb_init.py:init():494] updated telemetry
2021-09-29 10:43:08,278 INFO    MainThread:12568 [wandb_init.py:init():517] communicating current version
2021-09-29 10:43:08,637 INFO    MainThread:12568 [wandb_init.py:init():522] got version response 
2021-09-29 10:43:08,637 INFO    MainThread:12568 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-29 10:43:08,835 INFO    MainThread:12568 [wandb_init.py:init():557] starting run threads in backend
2021-09-29 10:43:08,922 INFO    MainThread:12568 [wandb_run.py:_console_start():1605] atexit reg
2021-09-29 10:43:08,922 INFO    MainThread:12568 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.REDIRECT
2021-09-29 10:43:08,922 INFO    MainThread:12568 [wandb_run.py:_redirect():1484] Redirecting console.
2021-09-29 10:43:08,924 INFO    MainThread:12568 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-29 10:43:08,925 INFO    MainThread:12568 [wandb_init.py:init():582] run started, returning control to user process
2021-09-29 11:24:42,086 INFO    MainThread:12568 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 1
2021-09-29 11:24:42,090 INFO    MainThread:12568 [wandb_run.py:_restore():1547] restore
2021-09-29 11:24:44,892 INFO    MainThread:12568 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1094
  total_bytes: 1094
}

2021-09-29 11:24:45,120 INFO    MainThread:12568 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1094
  total_bytes: 1094
}

2021-09-29 11:24:45,897 INFO    MainThread:12568 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1094
  total_bytes: 5767
}

2021-09-29 11:24:45,998 INFO    MainThread:12568 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1094
  total_bytes: 5767
}

2021-09-29 11:24:46,100 INFO    MainThread:12568 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4803
  total_bytes: 5767
}

2021-09-29 11:24:46,202 INFO    MainThread:12568 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5767
  total_bytes: 5767
}

2021-09-29 11:24:46,305 INFO    MainThread:12568 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5767
  total_bytes: 5767
}

2021-09-29 11:24:46,408 INFO    MainThread:12568 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5767
  total_bytes: 5767
}

2021-09-29 11:24:46,511 INFO    MainThread:12568 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5767
  total_bytes: 5767
}

2021-09-29 11:24:46,613 INFO    MainThread:12568 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5767
  total_bytes: 5767
}

2021-09-29 11:24:46,936 INFO    MainThread:12568 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5767
  total_bytes: 5767
}

2021-09-29 11:24:47,340 INFO    MainThread:12568 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5767
  total_bytes: 5767
}
local_info {
}

2021-09-29 11:24:48,443 INFO    MainThread:12568 [wandb_run.py:_show_files():1947] logging synced files
