
[34m[1mwandb[39m[22m: [33mWARNING[39m Symlinked 4 files into the W&B run directory, call wandb.save again to sync new files.
Vocab size:  103
Vocab size:  103
Epoch: 0/199 Phase: train Loss: 3.6077 (3.5966) Acc: 0.0078 (0.0078) Rec comedy: 0.0000 (nan):   0%|     | 3/1717 [00:00<06:33,  4.36it/s]
0.366337
[1447, 8259, 699, 5886, 65184, 2396, 31583, 1191, 37.6, 284, 23025, 3398, 6012, 30723, 2644, 6336, 1004, 1220, 2262, 2043, 313, 620, 1487, 1228, 2888, 925, 1041, 1123, 1106, 2972, 867, 736, 2735, 816, 213.0, 1994, 2646]






















































































































































































































Epoch: 0/199 Phase: train Loss: 3.4258 (3.3448) Acc: 0.0562 (0.0847) Rec comedy: 0.3830 (nan): 100%|â–ˆâ–ˆ| 1717/1717 [07:10<00:00,  3.99it/s]






















































Epoch: 0/199 Phase: valid Loss: 3.5647 (3.3842) Acc: 0.1162 (0.0500) Rec comedy: 0.4681 (nan): 100%|â–ˆâ–‰| 2742/2748 [01:49<00:00, 25.61it/s]
Epoch: 0/199 Phase: valid Loss: 3.5641 (2.3207) Acc: 0.1161 (0.5000) Rec comedy: 0.4681 (nan): 100%|â–ˆâ–ˆ| 2748/2748 [01:49<00:00, 25.08it/s]










































































































































Epoch: 1/199 Phase: train Loss: 3.2393 (2.8586) Acc: 0.1067 (0.1641) Rec comedy: 0.6316 (nan):  65%|â–ˆâ–Ž| 1116/1717 [04:39<02:30,  3.99it/s]
Traceback (most recent call last):
  File "train.py", line 358, in <module>
    wandb,
  File "train.py", line 97, in train
    outputs = model(seqs, lengths)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/konst/ml-utils/training/tagger_text/model.py", line 128, in forward
    x,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py", line 683, in forward
    self.num_layers, self.dropout, self.training, self.bidirectional)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED