
[34m[1mwandb[39m[22m: [33mWARNING[39m Symlinked 4 files into the W&B run directory, call wandb.save again to sync new files.
/usr/local/lib/python3.6/dist-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
/usr/local/lib/python3.6/dist-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)
4.873602
[3911753, 81108]
LR:  0.001


























































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































Epoch: 0/99 Phase: train Loss: 0.3266 (0.3515) Acc: 0.8074 (0.6207) Rec 1: 0.7710 (1.0000): 100%|â–ˆâ–ˆâ–ˆ| 31195/31195 [1:24:26<00:00,  6.16it/s]






































































Epoch: 0/99 Phase: valid Loss: 0.4629 (0.3902) Acc: 0.1052 (1.0000) Rec 1: 0.7903 (nan): 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4277/4277 [02:22<00:00, 30.10it/s]
Traceback (most recent call last):
  File "train.py", line 347, in <module>
    wandb,
  File "train.py", line 150, in train
    metrics.update({k + '_valid_rec': v for k, v in counts_rec.items()})
  File "train.py", line 150, in <dictcomp>
    metrics.update({k + '_valid_rec': v for k, v in counts_rec.items()})
TypeError: unsupported operand type(s) for +: 'int' and 'str'