2021-10-07 20:38:39,472 INFO    MainThread:16787 [wandb_setup.py:_flush():69] setting env: {}
2021-10-07 20:38:39,473 INFO    MainThread:16787 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '8bbaf831241b8525faf8ba0890cc99d295161186'}
2021-10-07 20:38:39,473 INFO    MainThread:16787 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '8bbaf831241b8525faf8ba0890cc99d295161186'}
2021-10-07 20:38:39,473 INFO    MainThread:16787 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-07 20:38:39,473 INFO    MainThread:16787 [wandb_init.py:_log_setup():342] Logging user logs to /root/konst/ml-utils/training/ner_employment/wandb/run-20211007_203839-gs9f8cac/logs/debug.log
2021-10-07 20:38:39,473 INFO    MainThread:16787 [wandb_init.py:_log_setup():343] Logging internal logs to /root/konst/ml-utils/training/ner_employment/wandb/run-20211007_203839-gs9f8cac/logs/debug-internal.log
2021-10-07 20:38:39,473 INFO    MainThread:16787 [wandb_init.py:init():375] calling init triggers
2021-10-07 20:38:39,473 INFO    MainThread:16787 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {'data_path': '/root/konst/data/bio_dataset/bio_ner_dataset.csv', 'checkpoint_path': '/root/konst/model_checkpoints/ner_employment', 'model_path': 'ner_base_epoch_84_acc_0.0759_vs_0.0115_loss_0.3195_vs_0.4482.pth', 'batch_size': 128, 'epochs': 160, 'start_epoch': 0, 'test_size': 0.05, 'lam': 0, 'patience': 5, 'factor': 0.5, 'use_wandb': True, 'lr': 0.001, 'save_at': 1, 'adjust_lr_every': 1, 'num_workers': 4}
2021-10-07 20:38:39,474 INFO    MainThread:16787 [wandb_init.py:init():424] starting backend
2021-10-07 20:38:39,474 INFO    MainThread:16787 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-07 20:38:39,486 INFO    MainThread:16787 [backend.py:ensure_launched():135] starting backend process...
2021-10-07 20:38:39,490 INFO    MainThread:16787 [backend.py:ensure_launched():140] started backend process with pid: 16812
2021-10-07 20:38:39,491 INFO    MainThread:16787 [wandb_init.py:init():429] backend started and connected
2021-10-07 20:38:39,493 INFO    MainThread:16787 [wandb_init.py:init():477] updated telemetry
2021-10-07 20:38:39,493 INFO    MainThread:16787 [wandb_init.py:init():500] communicating current version
2021-10-07 20:38:39,962 INFO    MainThread:16787 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-10-07 20:38:39,963 INFO    MainThread:16787 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-10-07 20:38:40,155 INFO    MainThread:16787 [wandb_init.py:init():540] starting run threads in backend
2021-10-07 20:38:40,905 INFO    MainThread:16787 [wandb_run.py:_console_start():1584] atexit reg
2021-10-07 20:38:40,905 INFO    MainThread:16787 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.REDIRECT
2021-10-07 20:38:40,906 INFO    MainThread:16787 [wandb_run.py:_redirect():1463] Redirecting console.
2021-10-07 20:38:40,907 INFO    MainThread:16787 [wandb_run.py:_redirect():1519] Redirects installed.
2021-10-07 20:38:40,907 INFO    MainThread:16787 [wandb_init.py:init():565] run started, returning control to user process
2021-10-07 20:39:59,017 INFO    MainThread:16787 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 1
2021-10-07 20:39:59,019 INFO    MainThread:16787 [wandb_run.py:_restore():1526] restore
2021-10-07 20:40:01,537 INFO    MainThread:16787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1238
  total_bytes: 1238
}

2021-10-07 20:40:01,774 INFO    MainThread:16787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1238
  total_bytes: 1238
}

2021-10-07 20:40:02,184 INFO    MainThread:16787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1238
  total_bytes: 9680
}

2021-10-07 20:40:02,287 INFO    MainThread:16787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1238
  total_bytes: 9680
}

2021-10-07 20:40:02,389 INFO    MainThread:16787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9653
  total_bytes: 9680
}

2021-10-07 20:40:02,492 INFO    MainThread:16787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9680
  total_bytes: 9680
}

2021-10-07 20:40:02,595 INFO    MainThread:16787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9680
  total_bytes: 9680
}

2021-10-07 20:40:02,697 INFO    MainThread:16787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9680
  total_bytes: 9680
}

2021-10-07 20:40:02,800 INFO    MainThread:16787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9680
  total_bytes: 9680
}

2021-10-07 20:40:03,186 INFO    MainThread:16787 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9680
  total_bytes: 9680
}

2021-10-07 20:40:03,289 INFO    MainThread:16787 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 9680
  total_bytes: 9680
}

2021-10-07 20:40:04,473 INFO    MainThread:16787 [wandb_run.py:_show_files():1898] logging synced files
