2021-12-27 15:35:52,908 INFO    MainThread:30730 [wandb_setup.py:_flush():69] setting env: {}
2021-12-27 15:35:52,908 INFO    MainThread:30730 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '8bbaf831241b8525faf8ba0890cc99d295161186'}
2021-12-27 15:35:52,908 INFO    MainThread:30730 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '8bbaf831241b8525faf8ba0890cc99d295161186'}
2021-12-27 15:35:52,908 INFO    MainThread:30730 [wandb_setup.py:_flush():69] setting login settings: {}
2021-12-27 15:35:52,909 INFO    MainThread:30730 [wandb_init.py:_log_setup():342] Logging user logs to /root/konst/ml-utils/training/tagger_text/wandb/run-20211227_153552-jvbtc9jg/logs/debug.log
2021-12-27 15:35:52,909 INFO    MainThread:30730 [wandb_init.py:_log_setup():343] Logging internal logs to /root/konst/ml-utils/training/tagger_text/wandb/run-20211227_153552-jvbtc9jg/logs/debug-internal.log
2021-12-27 15:35:52,909 INFO    MainThread:30730 [wandb_init.py:init():375] calling init triggers
2021-12-27 15:35:52,909 INFO    MainThread:30730 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {'data_path': '/root/konst/data/tags_text/tags_post_texts_v6.csv', 'checkpoint_path': '/root/konst/model_checkpoints/tagger_text', 'model_path': '', 'batch_size': 128, 'epochs': 200, 'start_epoch': 0, 'test_size': 0.2, 'lam': 0, 'patience': 8, 'factor': 0.5, 'use_wandb': True, 'lr': 0.001, 'save_at': 1, 'adjust_lr_every': 1, 'num_workers': 0}
2021-12-27 15:35:52,909 INFO    MainThread:30730 [wandb_init.py:init():424] starting backend
2021-12-27 15:35:52,909 INFO    MainThread:30730 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-12-27 15:35:52,921 INFO    MainThread:30730 [backend.py:ensure_launched():135] starting backend process...
2021-12-27 15:35:52,927 INFO    MainThread:30730 [backend.py:ensure_launched():140] started backend process with pid: 30747
2021-12-27 15:35:52,928 INFO    MainThread:30730 [wandb_init.py:init():429] backend started and connected
2021-12-27 15:35:52,931 INFO    MainThread:30730 [wandb_init.py:init():477] updated telemetry
2021-12-27 15:35:52,931 INFO    MainThread:30730 [wandb_init.py:init():500] communicating current version
2021-12-27 15:35:53,385 INFO    MainThread:30730 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-12-27 15:35:53,385 INFO    MainThread:30730 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-12-27 15:35:53,459 WARNING MainThread:30730 [wandb_init.py:init():795] interrupted
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 775, in init
    run = wi.init()
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/wandb_init.py", line 514, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 661, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 649, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 539, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/wandb/sdk/interface/interface.py", line 77, in get
    is_set = self._object_ready.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
