2021-11-08 19:41:06,116 INFO    MainThread:9785 [wandb_setup.py:_flush():69] setting env: {}
2021-11-08 19:41:06,116 INFO    MainThread:9785 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '8bbaf831241b8525faf8ba0890cc99d295161186'}
2021-11-08 19:41:06,116 INFO    MainThread:9785 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '8bbaf831241b8525faf8ba0890cc99d295161186'}
2021-11-08 19:41:06,116 INFO    MainThread:9785 [wandb_setup.py:_flush():69] setting login settings: {}
2021-11-08 19:41:06,116 INFO    MainThread:9785 [wandb_init.py:_log_setup():342] Logging user logs to /root/konst/ml-utils/training/toxic_deep/wandb/run-20211108_194106-244prrje/logs/debug.log
2021-11-08 19:41:06,116 INFO    MainThread:9785 [wandb_init.py:_log_setup():343] Logging internal logs to /root/konst/ml-utils/training/toxic_deep/wandb/run-20211108_194106-244prrje/logs/debug-internal.log
2021-11-08 19:41:06,117 INFO    MainThread:9785 [wandb_init.py:init():375] calling init triggers
2021-11-08 19:41:06,117 INFO    MainThread:9785 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {'data_path': '/root/konst/data/toxic_bio/toxic_bio_dataset.csv', 'checkpoint_path': '/root/konst/model_checkpoints/toxic_deep', 'model_path': '', 'batch_size': 128, 'epochs': 100, 'start_epoch': 0, 'test_size': 0.2, 'lam': 0, 'patience': 2, 'factor': 0.5, 'use_wandb': True, 'lr': 0.001, 'save_at': 1, 'adjust_lr_every': 1, 'num_workers': 0}
2021-11-08 19:41:06,117 INFO    MainThread:9785 [wandb_init.py:init():424] starting backend
2021-11-08 19:41:06,117 INFO    MainThread:9785 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-08 19:41:06,130 INFO    MainThread:9785 [backend.py:ensure_launched():135] starting backend process...
2021-11-08 19:41:06,136 INFO    MainThread:9785 [backend.py:ensure_launched():140] started backend process with pid: 9810
2021-11-08 19:41:06,137 INFO    MainThread:9785 [wandb_init.py:init():429] backend started and connected
2021-11-08 19:41:06,140 INFO    MainThread:9785 [wandb_init.py:init():477] updated telemetry
2021-11-08 19:41:06,140 INFO    MainThread:9785 [wandb_init.py:init():500] communicating current version
2021-11-08 19:41:06,694 INFO    MainThread:9785 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.6 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-11-08 19:41:06,694 INFO    MainThread:9785 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-11-08 19:41:07,552 INFO    MainThread:9785 [wandb_init.py:init():540] starting run threads in backend
2021-11-08 19:41:11,225 INFO    MainThread:9785 [wandb_run.py:_console_start():1584] atexit reg
2021-11-08 19:41:11,225 INFO    MainThread:9785 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.REDIRECT
2021-11-08 19:41:11,226 INFO    MainThread:9785 [wandb_run.py:_redirect():1463] Redirecting console.
2021-11-08 19:41:11,228 INFO    MainThread:9785 [wandb_run.py:_redirect():1519] Redirects installed.
2021-11-08 19:41:11,228 INFO    MainThread:9785 [wandb_init.py:init():565] run started, returning control to user process
2021-11-08 21:08:13,498 INFO    MainThread:9785 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 1
2021-11-08 21:08:13,498 INFO    MainThread:9785 [wandb_run.py:_restore():1526] restore
2021-11-08 21:08:16,091 INFO    MainThread:9785 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
  other_count: 4
}
pusher_stats {
  uploaded_bytes: 22833
  total_bytes: 22833
}

2021-11-08 21:08:16,306 INFO    MainThread:9785 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
  other_count: 4
}
pusher_stats {
  uploaded_bytes: 22833
  total_bytes: 22833
}

2021-11-08 21:08:16,417 INFO    MainThread:9785 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 4
  other_count: 4
}
pusher_stats {
  uploaded_bytes: 22833
  total_bytes: 33202
}

2021-11-08 21:08:16,519 INFO    MainThread:9785 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
  other_count: 4
}
pusher_stats {
  uploaded_bytes: 22833
  total_bytes: 33231
}

2021-11-08 21:08:16,622 INFO    MainThread:9785 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
  other_count: 4
}
pusher_stats {
  uploaded_bytes: 22833
  total_bytes: 33231
}

2021-11-08 21:08:16,725 INFO    MainThread:9785 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
  other_count: 4
}
pusher_stats {
  uploaded_bytes: 33231
  total_bytes: 33231
}

2021-11-08 21:08:16,828 INFO    MainThread:9785 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
  other_count: 4
}
pusher_stats {
  uploaded_bytes: 33231
  total_bytes: 33231
}

2021-11-08 21:08:16,931 INFO    MainThread:9785 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
  other_count: 4
}
pusher_stats {
  uploaded_bytes: 33231
  total_bytes: 33231
}

2021-11-08 21:08:17,035 INFO    MainThread:9785 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
  other_count: 4
}
pusher_stats {
  uploaded_bytes: 33231
  total_bytes: 33231
}

2021-11-08 21:08:17,137 INFO    MainThread:9785 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
  other_count: 4
}
pusher_stats {
  uploaded_bytes: 33231
  total_bytes: 33231
}

2021-11-08 21:08:17,438 INFO    MainThread:9785 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
  other_count: 4
}
pusher_stats {
  uploaded_bytes: 33231
  total_bytes: 33231
}

2021-11-08 21:08:17,541 INFO    MainThread:9785 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
  other_count: 4
}
pusher_stats {
  uploaded_bytes: 33231
  total_bytes: 33231
}

2021-11-08 21:08:18,748 INFO    MainThread:9785 [wandb_run.py:_show_files():1898] logging synced files
