2021-10-05 00:13:31,533 INFO    MainThread:32304 [wandb_setup.py:_flush():69] setting env: {}
2021-10-05 00:13:31,533 INFO    MainThread:32304 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '8bbaf831241b8525faf8ba0890cc99d295161186'}
2021-10-05 00:13:31,533 INFO    MainThread:32304 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '8bbaf831241b8525faf8ba0890cc99d295161186'}
2021-10-05 00:13:31,533 INFO    MainThread:32304 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-05 00:13:31,533 INFO    MainThread:32304 [wandb_init.py:_log_setup():342] Logging user logs to /root/konst/ml-utils/training/ner_employment/wandb/run-20211005_001331-2rbvmp4k/logs/debug.log
2021-10-05 00:13:31,534 INFO    MainThread:32304 [wandb_init.py:_log_setup():343] Logging internal logs to /root/konst/ml-utils/training/ner_employment/wandb/run-20211005_001331-2rbvmp4k/logs/debug-internal.log
2021-10-05 00:13:31,534 INFO    MainThread:32304 [wandb_init.py:init():375] calling init triggers
2021-10-05 00:13:31,534 INFO    MainThread:32304 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {'data_path': '/root/konst/data/bio_dataset/bio_ner_dataset.csv', 'checkpoint_path': '/root/konst/model_checkpoints/ner_employment', 'model_path': '', 'batch_size': 128, 'epochs': 100, 'start_epoch': 0, 'test_size': 0.05, 'lam': 0, 'patience': 1, 'factor': 0.5, 'use_wandb': True, 'lr': 0.0001, 'save_at': 1, 'adjust_lr_every': 1, 'num_workers': 4}
2021-10-05 00:13:31,534 INFO    MainThread:32304 [wandb_init.py:init():424] starting backend
2021-10-05 00:13:31,534 INFO    MainThread:32304 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-05 00:13:31,547 INFO    MainThread:32304 [backend.py:ensure_launched():135] starting backend process...
2021-10-05 00:13:31,552 INFO    MainThread:32304 [backend.py:ensure_launched():140] started backend process with pid: 32319
2021-10-05 00:13:31,552 INFO    MainThread:32304 [wandb_init.py:init():429] backend started and connected
2021-10-05 00:13:31,554 INFO    MainThread:32304 [wandb_init.py:init():477] updated telemetry
2021-10-05 00:13:31,555 INFO    MainThread:32304 [wandb_init.py:init():500] communicating current version
2021-10-05 00:13:32,030 INFO    MainThread:32304 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-10-05 00:13:32,030 INFO    MainThread:32304 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-10-05 00:13:32,226 INFO    MainThread:32304 [wandb_init.py:init():540] starting run threads in backend
2021-10-05 00:13:32,986 INFO    MainThread:32304 [wandb_run.py:_console_start():1584] atexit reg
2021-10-05 00:13:32,987 INFO    MainThread:32304 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.REDIRECT
2021-10-05 00:13:32,987 INFO    MainThread:32304 [wandb_run.py:_redirect():1463] Redirecting console.
2021-10-05 00:13:32,989 INFO    MainThread:32304 [wandb_run.py:_redirect():1519] Redirects installed.
2021-10-05 00:13:32,989 INFO    MainThread:32304 [wandb_init.py:init():565] run started, returning control to user process
2021-10-05 00:15:15,025 INFO    MainThread:32304 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 1
2021-10-05 00:15:15,026 INFO    MainThread:32304 [wandb_run.py:_restore():1526] restore
2021-10-05 00:15:17,807 INFO    MainThread:32304 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1135
  total_bytes: 1135
}

2021-10-05 00:15:18,071 INFO    MainThread:32304 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1135
  total_bytes: 1135
}

2021-10-05 00:15:18,264 INFO    MainThread:32304 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 3
}
pusher_stats {
  uploaded_bytes: 1135
  total_bytes: 6861
}

2021-10-05 00:15:18,367 INFO    MainThread:32304 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1135
  total_bytes: 7833
}

2021-10-05 00:15:18,468 INFO    MainThread:32304 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1135
  total_bytes: 7833
}

2021-10-05 00:15:18,570 INFO    MainThread:32304 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7833
  total_bytes: 7833
}

2021-10-05 00:15:18,673 INFO    MainThread:32304 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7833
  total_bytes: 7833
}

2021-10-05 00:15:18,779 INFO    MainThread:32304 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7833
  total_bytes: 7833
}

2021-10-05 00:15:18,882 INFO    MainThread:32304 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7833
  total_bytes: 7833
}

2021-10-05 00:15:18,985 INFO    MainThread:32304 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7833
  total_bytes: 7833
}

2021-10-05 00:15:19,324 INFO    MainThread:32304 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7833
  total_bytes: 7833
}

2021-10-05 00:15:19,427 INFO    MainThread:32304 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 7833
  total_bytes: 7833
}

2021-10-05 00:15:20,614 INFO    MainThread:32304 [wandb_run.py:_show_files():1898] logging synced files
